- platform: mjpeg
  mjpeg_url: !secret fd_url
  name: Front Drive
- platform: mjpeg
  mjpeg_url: !secret bgdn_url
  name: Back Garden
- platform: mjpeg
  mjpeg_url: !secret con_url
  name: Conservatory
- platform: mjpeg
  mjpeg_url: !secret office_url
  name: Office
