alias: 'Trigger Alarm Away'
hide_entity: True
trigger:
  - platform: state
    entity_id: group.downstairsmotion
    state: 'on'
  - platform: state
    entity_id: group.upstairsmotion
    state: 'on'        
condition:
  condition: state
  entity_id: alarm_control_panel.alarm
  state: armed_away
action:
  - service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.alarm
  - service: notify.email
    data:
      title: 'Alarm Activated'
      message: 'Alarm activated'
