alias: 'Trigger Alarm Away'
hide_entity: True
trigger:
  - platform: state
    entity_id: group.downstairsmotion
    to: 'on'
  - platform: state
    entity_id: group.upstairsmotion
    to: 'on'        
condition:
  condition: state
  entity_id: alarm_control_panel.alarm
  state: armed_away
action:
  - service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.alarm
  - service: notify.email
    data:
      title: 'House Alarm Activated'
      Message: 'Alarm Activated'
      
      
      #Message: Sensor {{ trigger.to_state.attributes.friendly_name }} triggered - {{ trigger.to_state.state }}.
      
      
      #message: >-
      #  {%- for state in states.sensor if state.entity_id == trigger.entity_id -%}
      #    {{ state.attributes.friendly_name }} Triggered The Alarm.
      #  {%- endfor -%}
