alias: 'Trigger Alarm Home'
hide_entity: True
trigger:
  - platform: state
    entity_id: group.downstairsmotion
    to: 'on'
condition:
  condition: state
  entity_id: alarm_control_panel.alarm
  state: armed_home
action:
  - service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.alarm
  - service: notify.email
    data:
      title: 'Alarm Activated'
      message: 'Alarm activated'
