alias: 'Bathroom Light On'
hide_entity: True
trigger:
  - platform: state
    entity_id: binary_sensor.fibaro_system_fgms001_motion_sensor_sensor_8_0
    state: 'on'
  - platform: state
    entity_id: binary_sensor.fibaro_system_fgms001_motion_sensor_sensor_16_0
    state: 'on'
condition:
  condition: time
  after: '06:00:00'
  before: '23:59:59' 
action:
  - service: scene.turn_on
    entity_id: scene.bathroom_normal
