alias: 'Bathroom Light Off'
hide_entity: True
trigger:
  - platform: state
    entity_id: binary_sensor.fibaro_system_fgms001_motion_sensor_sensor_8_0
    to: 'off'
    for:
      minutes: 6
      seconds: 0
action:
  - service: homeassistant.turn_off
    entity_id: group.bathroom_spots
