alias: 'Conservatory Light On When Dark'
hide_entity: True
trigger:
  - platform: state
    entity_id: binary_sensor.fibaro_system_fgms001_motion_sensor_sensor_12_0
    to: 'on'
condition:
  condition: state
  entity_id: sun.sun
  state: 'below_horizon'
  #condition: time
  #after: '17:00:00'
  #before: '09:00:00' 
action:
  - service: switch.turn_on
    data:
      entity_id: switch.fibaro_system_fgs212_switch_3kw_switch_20_0
