alias: 'Conservatory Lights Off'
hide_entity: True
trigger:
  - platform: state
    entity_id: binary_sensor.fibaro_system_fgms001_motion_sensor_sensor_12_0
    to: 'off'
    for:
      minutes: 5
      seconds: 0
action:
  - service: switch.turn_off
    entity_id: switch.fibaro_system_fgs212_switch_3kw_switch_20_0
