alias: 'Kitchen Light Off'
hide_entity: True
trigger:
  - platform: state
    entity_id: binary_sensor.fibaro_system_fgms001_motion_sensor_sensor_6_0
    to: 'off'
    for:
      minutes: 5
      seconds: 0
action:
  - service: homeassistant.turn_off
    entity_id: group.kitchen_spots
