alias: 'Switch Clock Off'
hide_entity: True
trigger:
  - platform: state
    entity_id: binary_sensor.fibaro_system_fgms001_motion_sensor_sensor_4_0
    to: 'off'
    for:
      minutes: 30
      seconds: 30
action:
  - service: switch.turn_off
    entity_id: switch.greenwave_powernode_1_port_switch_2_0
