alias: 'Outside Light Off'
hide_entity: True
trigger:
  - platform: state
    entity_id: binary_sensor.fibaro_system_fgms001_motion_sensor_sensor_13_0
    to: 'off'
    for:
      minutes: 2
      seconds: 0
action:
  - service: light.turn_off
    entity_id: light.front_drive
