alias: 'Roys Light On'
hide_entity: True
trigger:
  - platform: state
    binary_sensor.fibaro_system_fgms001_motion_sensor_sensor_7_0
    state: 'on'
condition:
  condition: time
  after: '07:00:00'
  before: '22:00:00' 
action:
  - service: scene.turn_on
    entity_id: scene.roy_normal
