alias: 'Roys Woke Up'
hide_entity: True
trigger:
  - platform: state
    entity_id: input_boolean.roy_waking_up
    to: 'on'
    for:
      minutes: 15
      seconds: 0

action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.roy_waking_up
