alias: 'Security Lights On'
hide_entity: True
trigger:
  - platform: state
    entity_id: binary_sensor.fibaro_system_fgms001zw5_motion_sensor_sensor_22_0
    state: 'on'
  - platform: state
    entity_id: binary_sensor.fibaro_system_fgms001zw5_motion_sensor_sensor_23_0
    state: 'on'
condition:
  condition: state
  entity_id: sun.sun
  state: 'below_horizon'
  #condition: time
  #after: '17:00:00'
  #before: '09:00:00' 
action:
  - service: switch.turn_on
    data:
      entity_id: switch.fibaro_system_fgs222_double_relay_switch_2x15kw_switch_21_0_2
