alias: 'Security Light Off'
hide_entity: True
trigger:
  - platform: state
    entity_id: binary_sensor.fibaro_system_fgms001zw5_motion_sensor_sensor_22_0
    to: 'off'
    for:
      minutes: 5
      seconds: 0
action:
  - service: switch.turn_off
    entity_id: switch.fibaro_system_fgs222_double_relay_switch_2x15kw_switch_21_0_2
